application: transfer-proxy-server
version: chat2
runtime: python27
api_version: 1
threadsafe: true
inbound_services:
  - channel_presence

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (.*/\.svn/.*)|
 (.*/Thumbs\.db)
 )$

handlers:

- url: /
  static_files: main.html
  upload: main.html

- url: /jquery.js
  static_files: jquery.js
  upload: jquery.js

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  mime_type: image/x-icon

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: main.app

